Repository rackspace/runway, pull requests merged in 2020-03, with the labels that each got.

#181 runway => cfngin integration improvements
  .vscode/settings.json
  CHANGELOG.md
  docs/Pipfile.lock
  docs/requirements.txt
  docs/source/cfngin/hooks.rst
  docs/source/cfngin/lookups.rst
  docs/source/module_configuration/cdk.rst
  docs/source/module_configuration/cloudformation.rst
  docs/source/module_configuration/serverless.rst
  docs/source/terminology.rst
  runway/cfngin/__init__.py
  runway/cfngin/cfngin.py
  runway/cfngin/commands/stacker/__init__.py
  runway/cfngin/config/__init__.py
  runway/cfngin/context.py
  runway/cfngin/hooks/aws_lambda.py
  runway/cfngin/session_cache.py
  runway/cfngin/util.py
  runway/cli.py
  runway/commands/base_command.py
  runway/commands/modules_command.py
  runway/commands/runway/run_stacker.py
  runway/context.py
  runway/module/cloudformation.py
  runway/util.py
  tests/cfngin/conftest.py
  tests/cfngin/fixtures/configs/basic.yml
  tests/cfngin/fixtures/envs/basic.env
  tests/cfngin/hooks/test_aws_lambda.py
  tests/cfngin/test_cfngin.py
  tests/cfngin/test_context.py
  tests/module/test_cloudformation.py
  tests/test_context.py
Labels: feature

#182 fix bug introduced in #181
  runway/util.py
Labels: bug, skip-changelog

#185 add editorconfig file
  .editorconfig
Labels: maintenance

#184 ssm lookup
  .vscode/settings.json
  CHANGELOG.md
  docs/source/cfngin/config.rst
  docs/source/cfngin/lookups.rst
  docs/source/lookups.rst
  docs/source/module_configuration/staticsite.rst
  docs/source/module_configuration/terraform.rst
  runway/cfngin/commands/stacker/__init__.py
  runway/cfngin/lookups/handlers/ssmstore.py
  runway/cfngin/lookups/registry.py
  runway/context.py
  runway/lookups/handlers/__init__.py
  runway/lookups/handlers/base.py
  runway/lookups/handlers/env.py
  runway/lookups/handlers/ssm.py
  runway/lookups/handlers/var.py
  runway/lookups/registry.py
  runway/module/staticsite.py
  runway/module/terraform.py
  runway/util.py
  setup.cfg
  tests/cfngin/lookups/test_registry.py
  tests/conftest.py
  tests/factories.py
  tests/lookups/handlers/test_base.py
  tests/lookups/handlers/test_ssm.py
  tests/lookups/test_registry.py
  tests/test_variables.py
Labels: feature

#188 update hook_data lookup to use standard query syntax
  CHANGELOG.md
  docs/source/cfngin/lookups.rst
  runway/cfngin/context.py
  runway/cfngin/lookups/handlers/hook_data.py
  runway/lookups/handlers/base.py
  runway/util.py
  tests/cfngin/lookups/handlers/test_hook_data.py
Labels: feature

#190 Callback URL Retriever for Auth@Edge
  runway/blueprints/staticsite/dependencies.py
  runway/hooks/staticsite/auth_at_edge/callback_url_retriever.py
  runway/hooks/staticsite/auth_at_edge/client_updater.py
  runway/hooks/staticsite/auth_at_edge/lambda_config.py
  runway/module/staticsite.py
Labels: feature

#195 fix runway module git path default location
  CHANGELOG.md
  runway/path.py
  tests/test_path.py
Labels: bug

#197 add stacker config deprecation warnings
  CHANGELOG.md
  runway/cfngin/config/__init__.py
Labels: feature

#198 catch AttributeError in cfngin diff for stack from persist graph
  CHANGELOG.md
  runway/cfngin/actions/diff.py
Labels: bug

#199 add cfngin stack termination protection
  CHANGELOG.md
  docs/source/cfngin/config.rst
  runway/cfngin/actions/build.py
  runway/cfngin/config/__init__.py
  runway/cfngin/providers/aws/default.py
  runway/cfngin/stack.py
  tests/cfngin/providers/aws/test_default.py
  tests/cfngin/test_config.py
Labels: feature

#193 [Bugfix] Lambda Execution Role Permissions Scope
  runway/blueprints/staticsite/auth_at_edge.py
  runway/blueprints/staticsite/staticsite.py
Labels: bug

#194 Auth@Edge User Pool Creation
  docs/source/module_configuration/staticsite.rst
  runway/blueprints/staticsite/dependencies.py
  runway/hooks/staticsite/auth_at_edge/callback_url_retriever.py
  runway/hooks/staticsite/auth_at_edge/client_updater.py
  runway/hooks/staticsite/auth_at_edge/domain_updater.py
  runway/hooks/staticsite/auth_at_edge/lambda_config.py
  runway/hooks/staticsite/auth_at_edge/user_pool_id_retriever.py
  runway/module/staticsite.py
Labels: feature

#206 restructure module type docs, reword some references to cfngin
  docs/source/cfngin/advanced_features.rst
  docs/source/cfngin/blueprints.rst
  docs/source/cfngin/configuration.rst
  docs/source/cfngin/directory_structure.rst
  docs/source/cfngin/environments.rst
  docs/source/cfngin/index.rst
  docs/source/cfngin/lookups.rst
  docs/source/cfngin/migrating.rst
  docs/source/index.rst
  docs/source/lookups.rst
  docs/source/module_configuration/cloudformation.rst
  docs/source/module_configuration/index.rst
  docs/source/terminology.rst
Labels: documentation

#208 fix cfngin diff output lookup resolution when no stack change
  CHANGELOG.md
  runway/cfngin/actions/diff.py
Labels: bug

#209 fix cfngin diff output lookup resolution when stack is locked
  CHANGELOG.md
  runway/cfngin/actions/diff.py
Labels: bug

#210 fix broken links in cfngin docs and spelling
  docs/source/cfngin/blueprints.rst
  docs/source/cfngin/hooks.rst
  docs/source/cfngin/lookups.rst
  docs/source/cfngin/templates.rst
Labels: documentation
