Repository rackspace/runway, pull requests merged in 2020-02, with the labels that each got.

#138 readd env file with only pipenv setting
  .env
Labels: enhancement

#142 replace stacker prefixed attrs, args, and config field with cfngin
  docs/source/cfngin/config.rst
  docs/source/cfngin/hooks.rst
  docs/source/cfngin/lookups.rst
  docs/source/cfngin/migrating.rst
  docs/source/getting_started.rst
  docs/source/runway_config.rst
  runway/cfngin/actions/base.py
  runway/cfngin/config/__init__.py
  runway/cfngin/context.py
  runway/cfngin/hooks/aws_lambda.py
  runway/cfngin/util.py
  runway/config.py
  tests/cfngin/test_config.py
  tests/cfngin/test_context.py
Labels: feature

#141 add markdownlint file, recommend extension, fix some lint warnings
  .markdownlint.yml
  .vscode/extensions.json
  CHANGELOG.md
  README.md
  integration_test_infrastructure/README.md
  integration_tests/README.md
  runway/templates/cdk-tsc/README.md
  runway/templates/k8s-cfn-repo/README.md
  runway/templates/k8s-tf-repo/README.md
Labels: maintenance

#145 pinned version to fix build errors, fixed error in pyinstaller artifacts
  .travis/install.sh
  Pipfile
  docs/source/developers.rst
  runway.file.spec
  runway.folder.spec
Labels: bug

#148 fix reverse_deployments to work with variable attributes
  runway/commands/modules_command.py
  runway/config.py
Labels: bug

#147 cfngin persistent graph
  docs/source/cfngin/config.rst
  docs/source/terminology.rst
  integration_tests/test_cfngin/tests/15_destroy_removed.py
  integration_tests/test_cfngin/tests/fixtures/15_destroy_removed.1.yaml
  integration_tests/test_cfngin/tests/fixtures/15_destroy_removed.2.yaml
  runway/cfngin/actions/base.py
  runway/cfngin/actions/build.py
  runway/cfngin/actions/destroy.py
  runway/cfngin/actions/diff.py
  runway/cfngin/actions/graph.py
  runway/cfngin/actions/info.py
  runway/cfngin/commands/stacker/__init__.py
  runway/cfngin/config/__init__.py
  runway/cfngin/context.py
  runway/cfngin/exceptions.py
  runway/cfngin/plan.py
  runway/cfngin/providers/aws/default.py
  runway/cfngin/util.py
  setup.py
  tests/cfngin/actions/test_base.py
  tests/cfngin/actions/test_build.py
  tests/cfngin/actions/test_destroy.py
  tests/cfngin/providers/aws/test_default.py
  tests/cfngin/test_context.py
  tests/cfngin/test_plan.py
Labels: feature

#149 fix cfngin relative imports for use through stacker shim
  runway/cfngin/blueprints/base.py
  runway/cfngin/blueprints/testutil.py
  runway/cfngin/lookups/handlers/ami.py
  runway/cfngin/lookups/handlers/default.py
  runway/cfngin/lookups/handlers/dynamodb.py
  runway/cfngin/lookups/handlers/envvar.py
  runway/cfngin/lookups/handlers/file.py
  runway/cfngin/lookups/handlers/hook_data.py
  runway/cfngin/lookups/handlers/kms.py
  runway/cfngin/lookups/handlers/output.py
  runway/cfngin/lookups/handlers/rxref.py
  runway/cfngin/lookups/handlers/split.py
  runway/cfngin/lookups/handlers/ssmstore.py
  runway/cfngin/lookups/handlers/xref.py
  runway/cfngin/stack.py
Labels: bug

#146 fix ami lookup KeyError when response contains an ARI/AKI
  runway/cfngin/lookups/handlers/ami.py
  tests/cfngin/lookups/handlers/test_ami.py
Labels: bug

#126 Narrow module tags integration test role permissions
  integration_test_infrastructure/codebuild/common/codebuild_blueprints/codebuild.py
  integration_test_infrastructure/codebuild/common/codebuild_blueprints/iam_policy_builder.py
  integration_test_infrastructure/codebuild/common/codebuild_blueprints/iam_policy_builder_test.py
  integration_test_infrastructure/codebuild/common/runway.yml
  integration_test_infrastructure/codebuild/common/stacks.yml
  integration_tests/README.md
  integration_tests/test_cdk/policies.yaml
  integration_tests/test_moduletags/policies.yaml
  integration_tests/test_parallelism/policies.yaml
  integration_tests/test_serverless/policies.yaml
  integration_tests/test_serverless/templates/promotezip-multisrc-multizip.sls/serverless.yml
  integration_tests/test_serverless/templates/promotezip-multisrc-single-zip.sls/serverless.yml
  integration_tests/test_serverless/templates/promotezip-singlesrc-singlezip.sls/serverless.yml
  integration_tests/test_sources/test_sources.py
  integration_tests/test_terraform/policies.yaml
  integration_tests/test_terraform/terraform_test.tf/.gitignore
  integration_tests/test_terraform/test_terraform.py
Labels: maintenance

#143 add hook args lookup resolution with a test and doc updates
  docs/source/cfngin/config.rst
  runway/cfngin/hooks/utils.py
  tests/cfngin/hooks/test_utils.py
Labels: feature

#150 fix cfngin lookups missing dependencies method, add shim test script for travis
  .travis/test.sh
  .travis/test_shim.sh
  Makefile
  runway/lookups/handlers/base.py
Labels: bug

#153 fix terraform integration tests
  integration_test_infrastructure/codebuild/common/codebuild_blueprints/codebuild.py
  integration_tests/Pipfile.lock
  integration_tests/integration_test.py
  integration_tests/test_terraform/policies.yaml
  integration_tests/test_terraform/templates/runway-state.yml
  integration_tests/test_terraform/test_terraform.py
  integration_tests/test_terraform/tests/test_local_to_local_backend.py
  integration_tests/test_terraform/tests/test_local_to_s3_backend.py
  integration_tests/test_terraform/tests/test_provider.py
  integration_tests/test_terraform/tests/test_version.py
  integration_tests/test_terraform/tf_state.cfn/dev-us-east-1.env
  integration_tests/test_terraform/tf_state.cfn/tfstate.yaml
Labels: bug, skip-changelog

#155 fix command integration tests
  integration_tests/test_commands/policies.yaml
  integration_tests/test_commands/test_commands.py
  integration_tests/test_commands/tests/test_runtfenv.py
  integration_tests/test_commands/tests/test_stacker.py
Labels: bug, skip-changelog

#156 fix region selection when parallel_regions but not CI
  integration_tests/test_parallelism/test_parallelism.py
  integration_tests/test_parallelism/tests/test_default_to_series.py
  integration_tests/test_parallelism/tests/test_two_regions.py
  runway/commands/modules_command.py
Labels: bug

#157 fix cfngin integration test permissions
  integration_tests/test_cfngin/policies.yaml
Labels: bug, skip-changelog

#158 fix staticsite int tests missing dir
  integration_tests/test_staticsite/policies.yaml
  integration_tests/test_staticsite/test_staticsite.py
  integration_tests/test_staticsite/tests/test_basic_site.py
Labels: bug, skip-changelog

#131 Adding "type" to runway config and abstracting class_path detection.
  docs/source/runway_config.rst
  integration_tests/test_runway_module_type_detection/__init__.py
  integration_tests/test_runway_module_type_detection/fixtures/runway-suffix-cdk.yml
  integration_tests/test_runway_module_type_detection/fixtures/runway-suffix-cfn.yml
  integration_tests/test_runway_module_type_detection/fixtures/runway-suffix-k8s.yml
  integration_tests/test_runway_module_type_detection/fixtures/runway-suffix-sls.yml
  integration_tests/test_runway_module_type_detection/fixtures/runway-suffix-tf.yml
  integration_tests/test_runway_module_type_detection/fixtures/runway-suffix-web.yml
  integration_tests/test_runway_module_type_detection/fixtures/runway-type-cdk.yml
  integration_tests/test_runway_module_type_detection/fixtures/runway-type-cloudformation.yml
  integration_tests/test_runway_module_type_detection/fixtures/runway-type-kubernetes.yml
  integration_tests/test_runway_module_type_detection/fixtures/runway-type-serverless.yml
  integration_tests/test_runway_module_type_detection/fixtures/runway-type-static.yml
  integration_tests/test_runway_module_type_detection/fixtures/runway-type-terraform.yml
  integration_tests/test_runway_module_type_detection/fixtures/sampleapp.cdk/.gitkeep
  integration_tests/test_runway_module_type_detection/fixtures/sampleapp.cfn/.gitkeep
  integration_tests/test_runway_module_type_detection/fixtures/sampleapp.k8s/.gitkeep
  integration_tests/test_runway_module_type_detection/fixtures/sampleapp.sls/.gitkeep
  integration_tests/test_runway_module_type_detection/fixtures/sampleapp.tf/.gitkeep
  integration_tests/test_runway_module_type_detection/fixtures/sampleapp.web/.gitkeep
  integration_tests/test_runway_module_type_detection/fixtures/type_cdk/.gitkeep
  integration_tests/test_runway_module_type_detection/fixtures/type_cloudformation/.gitkeep
  integration_tests/test_runway_module_type_detection/fixtures/type_kubernetes/.gitkeep
  integration_tests/test_runway_module_type_detection/fixtures/type_serverless/.gitkeep
  integration_tests/test_runway_module_type_detection/fixtures/type_static/.gitkeep
  integration_tests/test_runway_module_type_detection/fixtures/type_terraform/.gitkeep
  integration_tests/test_runway_module_type_detection/policies.yaml
  integration_tests/test_runway_module_type_detection/test_runway_module_type_detection.py
  integration_tests/test_runway_module_type_detection/tests/test_suffix_type_cdk.py
  integration_tests/test_runway_module_type_detection/tests/test_suffix_type_cfn.py
  integration_tests/test_runway_module_type_detection/tests/test_suffix_type_k8s.py
  integration_tests/test_runway_module_type_detection/tests/test_suffix_type_sls.py
  integration_tests/test_runway_module_type_detection/tests/test_suffix_type_tf.py
  integration_tests/test_runway_module_type_detection/tests/test_suffix_type_web.py
  integration_tests/test_runway_module_type_detection/tests/test_type_cdk.py
  integration_tests/test_runway_module_type_detection/tests/test_type_cloudformation.py
  integration_tests/test_runway_module_type_detection/tests/test_type_kubernetes.py
  integration_tests/test_runway_module_type_detection/tests/test_type_serverless.py
  integration_tests/test_runway_module_type_detection/tests/test_type_static.py
  integration_tests/test_runway_module_type_detection/tests/test_type_terraform.py
  runway/commands/modules_command.py
  runway/config.py
  runway/module/staticsite.py
  runway/runway_module_type.py
  setup.py
Labels: feature

#159 fix sls race condition when trying to create & encrypt promotezip bucket
  CHANGELOG.md
  runway/s3_util.py
Labels: bug

#160 fix cfngin int test varying message suffix
  integration_tests/test_cfngin/tests/12_rollback_dependent.py
Labels: bug, skip-changelog

#161 remove PR actions, update release drafter action
  .github/auto_assign.yml
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/pr-management.yml
  .github/workflows/release-management.yml
  docs/source/developers.rst
Labels: maintenance

#164 nest "Type" under "Module" section
  docs/source/runway_config.rst
Labels: documentation

#163 Add --config option to serverless module
  CHANGELOG.md
  docs/source/module_configuration/serverless.rst
  runway/module/serverless.py
Labels: feature

#167 fix parallel_regions skipping subsequent deployments
  CHANGELOG.md
  runway/commands/modules_command.py
Labels: bug

#166 replace sls_configfile with args
  CHANGELOG.md
  docs/source/module_configuration/serverless.rst
  runway/module/serverless.py
Labels: feature

#140 Improvements to AWS Lambda Upload Hook
  .vscode/extensions.json
  .vscode/settings.json
  Pipfile.lock
  docs/source/cfngin/hooks.rst
  integration_tests/Pipfile.lock
  integration_tests/integration_test.py
  integration_tests/test_cfngin/tests/16_aws_lambda_hook.py
  integration_tests/test_cfngin/tests/fixtures/16_aws_lambda_hook.yaml
  integration_tests/test_cfngin/tests/fixtures/lambda_function.py
  integration_tests/test_cfngin/tests/fixtures/lambda_src/dockerize_src/Pipfile
  integration_tests/test_cfngin/tests/fixtures/lambda_src/dockerize_src/Pipfile.lock
  integration_tests/test_cfngin/tests/fixtures/lambda_src/dockerize_src/dockerize.py
  integration_tests/test_cfngin/tests/fixtures/lambda_src/dockerize_src/lib/__init__.py
  integration_tests/test_cfngin/tests/fixtures/lambda_src/nondockerize_src/Pipfile
  integration_tests/test_cfngin/tests/fixtures/lambda_src/nondockerize_src/Pipfile.lock
  integration_tests/test_cfngin/tests/fixtures/lambda_src/nondockerize_src/lib/__init__.py
  integration_tests/test_cfngin/tests/fixtures/lambda_src/nondockerize_src/nondockerize.py
  integration_tests/test_cfngin/tests/runway.yaml
  runway/cfngin/exceptions.py
  runway/cfngin/hooks/aws_lambda.py
  setup.py
  tests/cfngin/fixtures/mock_docker/__init__.py
  tests/cfngin/fixtures/mock_docker/fake_api.py
  tests/cfngin/fixtures/mock_docker/fake_api_client.py
  tests/cfngin/fixtures/mock_docker/fake_stat.py
  tests/cfngin/hooks/test_aws_lambda.py
Labels: feature

#165 v1.4.0
  CHANGELOG.md
  runway/__init__.py
Labels: feature, skip-changelog

#168 avoid npm directory creation errors
  npm/postinstall.js
Labels: bug

#170 remove use of README.rst and pandoc
  .travis.yml
  Makefile
  README.md
  README.rst
  setup.py
Labels: bug, skip-changelog

#169 adjust cfngin tests log message check
  CHANGELOG.md
  runway/cfngin/__init__.py
Labels: bug

#171 remove manual homebrew, set addon to update
  .travis.yml
Labels: maintenance

#172 pin back version of virualenv and pyinstaller to fix linux error
  .travis/install.sh
  Pipfile
  Pipfile.lock
  docs/source/developers.rst
  runway.file.spec
  runway.folder.spec
Labels: bug

#175 fix apidoc_module_dir post src removal
  docs/source/conf.py
Labels: documentation

#173 change cfngin.commands.__init__ import of __version__ to absolute
  CHANGELOG.md
  runway/cfngin/commands/stacker/__init__.py
Labels: bug

#174 add shim for stacker.variables
  CHANGELOG.md
  runway/__init__.py
  setup.py
Labels: bug

#177 configurable max concurrent parallel modules & regions
  CHANGELOG.md
  docs/source/developers.rst
  runway/commands/modules_command.py
  runway/context.py
Labels: feature

#178 Corrects an issue with variable lookup
  runway/variables.py
Labels: bug

#179 fix cfngin resolve complex variable types, fix runway config variables def
  .vscode/settings.json
  CHANGELOG.md
  runway/config.py
  runway/lookups/handlers/var.py
  runway/variables.py
Labels: bug
