Repository rackspace/runway, pull requests merged in 2020-06, with the labels that each got.

#339 the friendly error when npm can't be found has returned
  CHANGELOG.md
  runway/module/__init__.py
  tests/module/test_module.py
Labels: bug

#351 fix namespace collisions when cfngin modules contribute similar names
  CHANGELOG.md
  runway/cfngin/cfngin.py
  runway/util.py
  tests/cfngin/test_cfngin.py
  tests/fixtures/empty_module.py
  tests/test_util.py
Labels: bug

#335 restructure k8s docs
  docs/source/index.rst
  docs/source/kubernetes/advanced_features.rst
  docs/source/kubernetes/configuration.rst
  docs/source/kubernetes/directory_structure.rst
  docs/source/kubernetes/examples.rst
  docs/source/module_configuration/index.rst
  docs/source/module_configuration/kubernetes.rst
Labels: documentation

#332 change boto3-stubs to a dev dependency so it does not impact prod
  .github/scripts/urlshortener/Makefile
  .github/scripts/urlshortener/Pipfile
  .github/scripts/urlshortener/Pipfile.lock
  .github/scripts/urlshortener/requirements.txt
  .github/scripts/urlshortener/update_urls.py
Labels: maintenance

#341 add `future.strict_environment` config option
  .gitignore
  CHANGELOG.md
  docs/source/runway_config.rst
  runway/commands/modules_command.py
  runway/config.py
  runway/context.py
  tests/commands/test_modules_command.py
  tests/factories.py
  tests/test_config.py
  tests/test_context.py
Labels: feature

#353 sls-tsc template: migrate from tslint to typescript-eslint
  CHANGELOG.md
  runway/templates/sls-tsc/.eslintignore
  runway/templates/sls-tsc/.eslintrc.js
  runway/templates/sls-tsc/package.json
  runway/templates/sls-tsc/src/helloWorld.test.ts
  runway/templates/sls-tsc/src/helloWorld.ts
  runway/templates/sls-tsc/tslint.json
Labels: feature, priority:low

#350 disable pip red error messages; add pip warning
  CHANGELOG.md
  integration_tests/test_cfngin/tests/16_aws_lambda_hook.py
  integration_tests/test_cfngin/tests/fixtures/16_aws_lambda_hook.yaml
  integration_tests/test_cfngin/tests/fixtures/lambda_src/authatedge_src/index.py
  integration_tests/test_cfngin/tests/fixtures/lambda_src/authatedge_src/requirements.txt
  runway/cfngin/hooks/aws_lambda.py
Labels: enhancement

#354 improve test coverage of command base classes
  runway/commands/base_command.py
  runway/commands/modules_command.py
  runway/commands/runway_command.py
  setup.cfg
  tests/commands/test_base_command.py
  tests/commands/test_modules_command.py
  tests/commands/test_runway_command.py
  tests/conftest.py
  tests/factories.py
  tests/fixtures/configs/README.md
  tests/fixtures/configs/min_required.yml
  tests/fixtures/configs/min_required_multi.yml
  tests/fixtures/configs/simple_parallel_regions.1.yml
  tests/fixtures/configs/simple_parallel_regions.2.yml
  tests/fixtures/deployments/README.md
  tests/fixtures/deployments/environments_map_deprecated.yml
  tests/fixtures/deployments/environments_map_list.yml
  tests/fixtures/deployments/environments_map_str.yml
  tests/fixtures/deployments/min_required.yml
  tests/fixtures/deployments/min_required_multi.yml
  tests/fixtures/deployments/simple_assume_role.yml
  tests/fixtures/deployments/simple_env_vars.yml
  tests/fixtures/deployments/simple_env_vars_map.yml
  tests/fixtures/deployments/simple_parallel_module.yml
  tests/fixtures/deployments/tagged_multi.yml
  tests/fixtures/deployments/tagged_single.yml
  tests/fixtures/deployments/validate_account.yml
  tests/fixtures/deployments/validate_account_map.yml
  tests/fixtures/tag.runway.yml
Labels: maintenance

#358 [BUG-356] - Add support for serverless module names
  runway/commands/modules_command.py
  runway/module/__init__.py
Labels: bug

#338 restructure developers guide & move custom module doc page
  .vscode/settings.json
  docs/source/developers/custom_module.rst
  docs/source/developers/index.rst
  docs/source/developers/maintainers/index.rst
  docs/source/index.rst
  docs/source/maintainers/infrastructure.rst
  docs/source/maintainers/labels.rst
  docs/source/maintainers/release_process.rst
  docs/source/module_configuration/index.rst
Labels: documentation

#361 fix RunwayModule not subscriptable & awacs/troposphere unload causing isinstance inconsistencies
  runway/cfngin/cfngin.py
  runway/module/__init__.py
  runway/util.py
  tests/cfngin/test_cfngin.py
  tests/test_util.py
Labels: bug, priority:critical

#359 add prompt to select region for envvars command
  runway/commands/runway/__init__.py
  runway/commands/runway/envvars.py
  tests/commands/runway_commands/__init__.py
  tests/commands/runway_commands/test_envvars.py
Labels: bug

#367 fix issue where sys.path was not fully reverted between cfngin configs
  CHANGELOG.md
  runway/cfngin/cfngin.py
Labels: bug

#372 allow runway tests to exit 0 without signaling failure
  runway/commands/runway/test.py
Labels: bug

#373 update runway blueprints link
  docs/source/cfngin/blueprints.rst
Labels: documentation
