Repository rackspace/runway, pull requests merged in 2020-05, with the labels that each got.

#267 fix path to lookup handler, fix link to runway config
  docs/source/cfngin/configuration.rst
  docs/source/cfngin/lookups.rst
Labels: documentation

#268 add ability to extend a serverless.yml from runway.yml
  .vscode/settings.json
  CHANGELOG.md
  Makefile
  docs/source/runway_config.rst
  docs/source/serverless/advanced_features.rst
  docs/source/serverless/configuration.rst
  runway/module/__init__.py
  runway/module/serverless.py
  setup.cfg
  tests/factories.py
  tests/module/conftest.py
  tests/module/test_module.py
  tests/module/test_serverless.py
Labels: feature

#274 fix the example header
  docs/source/runway_config.rst
Labels: documentation

#276 fix broken link to quickstarts on README
  README.md
Labels: documentation

#279 aws_lambda hook can use internal pip when zipping dependencies
  CHANGELOG.md
  runway.file.spec
  runway.folder.spec
  runway/cfngin/hooks/aws_lambda.py
  tests/cfngin/hooks/test_aws_lambda.py
Labels: bug

#281 lookup arg parse handle `=` in value
  CHANGELOG.md
  runway/lookups/handlers/base.py
  tests/lookups/handlers/test_base.py
Labels: bug

#282 replace uses of "class_path: ...StaticSite" with "type: static"
  integration_tests/test_staticsite/fixtures/runway-basic-site.yml
  quickstarts/conduit/runway.yml
  runway/templates/static-angular/runway.yml
  runway/templates/static-react/runway.yml
Labels: bug

#284 cfnlint now invoked with runpy.run_module, warn when missing templates
  CHANGELOG.md
  runway/tests/handlers/cfn_lint.py
Labels: bug

#270 Update static angular template to use npx
  runway/templates/static-angular/runway.yml
Labels: bug

#288 add py wheel package to urlshortener action
  .github/workflows/cicd.yml
Labels: maintenance

#290 add logic to use `--no-color` with cdk, cpm, sls, and tf
  CHANGELOG.md
  docs/source/conf.py
  docs/source/developers/advanced_configuration.rst
  docs/source/serverless/advanced_features.rst
  docs/source/terraform/advanced_features.rst
  runway/context.py
  runway/module/__init__.py
  runway/module/cdk.py
  runway/module/serverless.py
  runway/module/terraform.py
  tests/module/test_module.py
  tests/module/test_serverless.py
  tests/test_context.py
Labels: feature

#289 destroy_stack now aware of action=diff, use different approval prompt
  CHANGELOG.md
  runway/cfngin/providers/aws/default.py
Labels: feature

#326 a@e refresh token with 5 minutes remaining
  CHANGELOG.md
  runway/hooks/staticsite/auth_at_edge/templates/check_auth/__init__.py
Labels: feature

#329 runway test: return non-zero exit code if any non-required tests failed
  CHANGELOG.md
  docs/source/defining_tests.rst
  runway/commands/runway/test.py
Labels: feature

#330 remove yarn from static-react sample
  CHANGELOG.md
  docs/source/quickstart/private_static_site.rst
  runway/templates/static-react/runway.yml
  runway/templates/static-react/sample-app/.gitignore
  runway/templates/static-react/sample-app/README.md
  runway/templates/static-react/sample-app/package.json
  runway/templates/static-react/sample-app/public/robots.txt
Labels: feature

#334 restructured staticsite docs
  .vscode/settings.json
  docs/source/conf.py
  docs/source/index.rst
  docs/source/module_configuration/index.rst
  docs/source/module_configuration/staticsite.rst
  docs/source/staticsite/advanced_features.rst
  docs/source/staticsite/configuration.rst
  docs/source/staticsite/directory_structure.rst
  docs/source/staticsite/examples.rst
Labels: documentation

#331 update cfn template to use new cfngin_bucket syntax
  runway/templates/cfn/dev-us-east-1.env
  runway/templates/cfn/stacks.yaml
Labels: maintenance

#344 fix Pyinstaller yamllint test
  CHANGELOG.md
  runway.file.spec
  runway.folder.spec
  runway/tests/handlers/yaml_lint.py
Labels: bug
