Repository rackspace/runway, pull requests merged in 2020-09, with the labels that each got.

#439 relocate, update, and rename variable & lookup exceptions
  runway/cfngin/blueprints/base.py
  runway/cfngin/blueprints/raw.py
  runway/cfngin/exceptions.py
  runway/cfngin/hooks/utils.py
  runway/cfngin/lookups/registry.py
  runway/core/components/_deployment.py
  runway/exceptions.py
  runway/lookups/handlers/cfn.py
  runway/module/cloudformation.py
  runway/variables.py
  tests/unit/cfngin/blueprints/test_base.py
  tests/unit/cfngin/lookups/handlers/test_hook_data.py
  tests/unit/cfngin/lookups/test_registry.py
  tests/unit/cfngin/test_cfngin.py
  tests/unit/core/components/test_deployment.py
  tests/unit/lookups/handlers/test_cfn.py
  tests/unit/lookups/handlers/test_ssm.py
  tests/unit/module/test_cloudformation.py
  tests/unit/test_config.py
  tests/unit/test_variables.py
Labels: feature

#440 remove stacker shim and update documentation to remove mentions of it
  .github/scripts/cicd/test_shim.sh
  Makefile
  docs/source/cfngin/migrating.rst
  integration_test_infrastructure/alt_account_role/common/role_blueprints/iam.py
  integration_tests/test_commands/fixtures/buildpipeline.py
  integration_tests/test_moduletags/sampleapp/blueprints/fake_stack.py
  runway/__init__.py
  runway/cfngin/__init__.py
  runway/cfngin/commands/stacker/__init__.py
  tests/integration/cli/commands/test_run_stacker.py
Labels: feature

#444 fix cfngin kms lookup on py3
  CHANGELOG.md
  runway/cfngin/lookups/handlers/kms.py
  tests/unit/cfngin/lookups/handlers/test_kms.py
Labels: bug, priority:low

#442 fix `YamlDirTestGenerator` python 3 compatibility
  CHANGELOG.md
  runway/cfngin/blueprints/testutil.py
Labels: bug

#448 fix issue causing static sites to be inaccessible when not us-east-1
  CHANGELOG.md
  runway/blueprints/staticsite/staticsite.py
Labels: bug

#449 fix `npx runway <command>` (npm) not recognized on Windows
  CHANGELOG.md
  npm/postinstall.js
Labels: bug

#429 add handling for `plan` when `cfngin_bucket` does not exist
  .github/workflows/cicd.yml
  CHANGELOG.md
  pyproject.toml
  runway/__init__.py
  runway/cfngin/actions/diff.py
  runway/cfngin/commands/stacker/__init__.py
  runway/core/providers/aws/__init__.py
  runway/core/providers/aws/_response.py
  runway/core/providers/aws/s3/__init__.py
  runway/core/providers/aws/s3/_bucket.py
  runway/http_backport.py
  runway/module/cloudformation.py
  tests/unit/cfngin/actions/test_diff.py
  tests/unit/conftest.py
  tests/unit/core/providers/aws/s3/__init__.py
  tests/unit/core/providers/aws/s3/test_bucket.py
  tests/unit/core/providers/aws/test_response.py
Labels: feature

#450 remove `runway.http_backport`
  .github/workflows/cicd.yml
  pyproject.toml
  runway/core/providers/aws/_response.py
  runway/core/providers/aws/s3/_bucket.py
  runway/hooks/staticsite/cleanup.py
  runway/http_backport.py
  tests/unit/core/providers/aws/s3/test_bucket.py
Labels: feature

#451 static site CF origin will now use the s3 regional endpoint to avoid temporary redirect for new deployments
  CHANGELOG.md
  runway/blueprints/staticsite/staticsite.py
Labels: bug
