Repository rackspace/runway, pull requests merged in 2020-07, with the labels that each got.

#374 update macOS python setup docs to default to zsh
  docs/source/python_setup.rst
Labels: documentation

#337 Fix npm subprocess execution on Ubuntu 20.04
  runway/module/__init__.py
Labels: bug, priority:medium

#376 add additional terraform backend init arguments
  runway/module/terraform.py
Labels: feature

#377 fix Kubernetes section caption
  docs/source/index.rst
Labels: documentation

#378 fix promotezip with serverless@<1.70.0
  CHANGELOG.md
  integration_tests/test_serverless/templates/promotezip-multisrc-multizip.sls/package-lock.json
  integration_tests/test_serverless/templates/promotezip-multisrc-multizip.sls/package.json
  integration_tests/test_serverless/templates/promotezip-multisrc-single-zip.sls/package-lock.json
  integration_tests/test_serverless/templates/promotezip-multisrc-single-zip.sls/package.json
  integration_tests/test_serverless/templates/promotezip-singlesrc-singlezip.sls/package-lock.json
  integration_tests/test_serverless/templates/promotezip-singlesrc-singlezip.sls/package.json
  runway/module/serverless.py
Labels: bug

#368 staticsite extra_files
  CHANGELOG.md
  docs/Pipfile
  docs/Pipfile.lock
  docs/requirements.txt
  docs/source/cfngin/hooks.rst
  docs/source/staticsite/advanced_features.rst
  docs/source/staticsite/configuration.rst
  docs/source/staticsite/examples.rst
  runway/hooks/staticsite/upload_staticsite.py
  runway/module/staticsite.py
  tests/hooks/__init__.py
  tests/hooks/staticsite/__init__.py
  tests/hooks/staticsite/test_upload_staticsite.py
Labels: feature

#381 fixed issue where tests were not properly excluded from distributable
  setup.py
Labels: bug

#386 update sls autodetect to check for serverless.ts
  CHANGELOG.md
  runway/runway_module_type.py
  tests/unit/test_runway_module_type.py
Labels: feature

#384 fix aws alias/id validation when assumed and async
  CHANGELOG.md
  runway/core/components/_deployment.py
  tests/unit/core/components/test_deployment.py
Labels: bug

#389 update log msgs from config to match the format of other log msgs
  runway/config.py
  tests/unit/test_config.py
Labels: bug

#393 document reqs for return to be added to hook_data
  docs/source/cfngin/hooks.rst
Labels: documentation

#387 add cfn lookup
  CHANGELOG.md
  docs/Makefile
  docs/source/cfngin/lookups.rst
  docs/source/lookups.rst
  docs/source/terraform/advanced_features.rst
  runway/cfngin/lookups/handlers/xref.py
  runway/cfngin/lookups/registry.py
  runway/cfngin/providers/aws/default.py
  runway/lookups/handlers/__init__.py
  runway/lookups/handlers/base.py
  runway/lookups/handlers/cfn.py
  runway/lookups/handlers/ssm.py
  runway/lookups/handlers/var.py
  runway/lookups/registry.py
  runway/module/terraform.py
  tests/unit/lookups/handlers/test_cfn.py
  tests/unit/lookups/test_registry.py
Labels: feature
