Repository rackspace/runway, pull requests merged in 2020-10, with the labels that each got.

#469 cfngin: change jinja2 template loading to Environment
  runway/cfngin/blueprints/raw.py
Labels: feature, priority:low

#471 CFNgin will now ignore bitbucket-pipeline.yml when finding config files
  CHANGELOG.md
  runway/cfngin/cfngin.py
  tests/unit/cfngin/test_cfngin.py
Labels: feature

#472 broaden urllib3 pin to accommodate botocore>=1.19
  CHANGELOG.md
  Pipfile.lock
  setup.py
Labels: dependencies

#477 update dependencies in lock files (only effects binary releases)
  Pipfile.lock
  docs/Pipfile.lock
  docs/requirements.txt
  integration_test_infrastructure/Pipfile.lock
  integration_tests/Pipfile.lock
Labels: dependencies
