Repository rackspace/runway, pull requests merged in 2020-04, with the labels that each got.

#214 wrap cfngin run with a ctx manager that temp updates os.environ from ctx
  CHANGELOG.md
  runway/cfngin/cfngin.py
  runway/util.py
  tests/cfngin/test_cfngin.py
  tests/test_util.py
Labels: bug

#211 Documentation Fixing link for CFNgin on modules page
  docs/source/runway_config.rst
Labels: documentation

#212 Fix config error in example snippet for auth@edge
  docs/source/module_configuration/staticsite.rst
Labels: documentation

#200 add acm certificate hook
  .vscode/settings.json
  docs/source/cfngin/hooks.rst
  runway/cfngin/exceptions.py
  runway/cfngin/hooks/acm.py
  runway/cfngin/hooks/base.py
  runway/cfngin/hooks/utils.py
  runway/cfngin/status.py
  tests/cfngin/hooks/test_acm.py
  tests/cfngin/hooks/test_base.py
  tests/cfngin/hooks/test_utils.py
  tests/conftest.py
Labels: feature

#216 add lookup resolution to envvars command
  CHANGELOG.md
  runway/commands/runway/envvars.py
Labels: bug

#215 fix integration tests
  integration_tests/test_moduletags/test_moduletags.py
Labels: bug, maintenance, skip-changelog

#218 update formatting of cdk docs
  .vscode/settings.json
  docs/source/cdk/advanced_features.rst
  docs/source/cdk/configuration.rst
  docs/source/cdk/directory_structure.rst
  docs/source/index.rst
  docs/source/module_configuration/cdk.rst
  docs/source/module_configuration/index.rst
Labels: documentation

#217 update formatting of sls module docs
  .vscode/settings.json
  docs/source/index.rst
  docs/source/module_configuration/index.rst
  docs/source/module_configuration/serverless.rst
  docs/source/serverless/advanced_features.rst
  docs/source/serverless/configuration.rst
  docs/source/serverless/directory_structure.rst
Labels: documentation

#220 make regex more inclusive
  .github/workflows/branch-name.yml
Labels: maintenance

#219 fixed terraform array parameters serialization
  runway/module/terraform.py
  tests/module/test_terraform.py
Labels: bug

#221 update formatting of tf module docs
  .vscode/settings.json
  docs/source/index.rst
  docs/source/module_configuration/index.rst
  docs/source/module_configuration/terraform.rst
  docs/source/terraform/advanced_features.rst
  docs/source/terraform/configuration.rst
  docs/source/terraform/directory_structure.rst
Labels: documentation

#222 Bugfix/template safe sub
  CHANGELOG.md
  runway/cfngin/config/__init__.py
Labels: bug

#223 update variable.runway.yml to runway.variables.yml
  docs/source/runway_config.rst
Labels: documentation

#224 fix get_config_directory when used within cfngin
  .vscode/settings.json
  CHANGELOG.md
  runway/cfngin/cfngin.py
  runway/util.py
  tests/test_util.py
Labels: bug

#201 StaticSite Cleanup State Machine
  runway/blueprints/staticsite/auth_at_edge.py
  runway/blueprints/staticsite/cleanup.py
  runway/blueprints/staticsite/staticsite.py
  runway/blueprints/staticsite/templates/replicated_lambda_remover.template.py
  runway/blueprints/staticsite/templates/self_destruct.template.py
  runway/cfngin/util.py
  runway/hooks/staticsite/auth_at_edge/domain_updater.py
  runway/hooks/staticsite/cleanup.py
  runway/module/staticsite.py
Labels: feature

#227 reload hooks between uses
  CHANGELOG.md
  runway/cfngin/hooks/utils.py
  runway/util.py
  tests/cfngin/hooks/test_utils.py
  tests/fixtures/__init__.py
  tests/fixtures/mock_hooks.py
  tests/test_util.py
Labels: bug

#229 add prompt for deploy env when branch name is unexpected
  CHANGELOG.md
  runway/commands/modules_command.py
  runway/commands/runway_command.py
  runway/context.py
  tests/commands/test_modules_command.py
  tests/commands/test_runway_command.py
Labels: feature

#230 revert context.hook_data data type to dict
  CHANGELOG.md
  runway/cfngin/context.py
  runway/cfngin/lookups/handlers/hook_data.py
  tests/cfngin/test_context.py
Labels: bug

#234 add handling for depedabot PRs
  .github/release-drafter.yml
  .github/workflows/branch-name.yml
Labels: maintenance

#189 travis => actions
  .editorconfig
  .github/scripts/README.md
  .github/scripts/cicd/build_pyinstaller.sh
  .github/scripts/cicd/test_shim.sh
  .github/workflows/cicd.yml
  .pylintrc
  .travis.yml
  .travis/install.sh
  .travis/test.sh
  .vscode/extensions.json
  .vscode/settings.json
  Makefile
  Pipfile
  Pipfile.lock
  README.md
  docs/Pipfile.lock
  docs/source/conf.py
  docs/source/developers.rst
  docs/source/developers/advanced_configuration.rst
  docs/source/developers/contributing.rst
  docs/source/developers/getting_started.rst
  docs/source/developers/github_actions.rst
  docs/source/developers/index.rst
  docs/source/developers/maintainers/index.rst
  docs/source/developers/maintainers/labels.rst
  docs/source/developers/maintainers/release_process.rst
  docs/source/developers/pyinstaller.rst
  docs/source/index.rst
  docs/source/terminology.rst
  integration_test_infrastructure/Pipfile.lock
  integration_tests/Pipfile.lock
  runway.file.spec
  runway.folder.spec
  runway/__init__.py
  runway/cfngin/actions/base.py
  runway/cfngin/actions/build.py
  runway/cfngin/hooks/aws_lambda.py
  setup.py
Labels: maintenance

#235 fix npm build artifact, pypi publish artifact download, setup-node
  .github/scripts/cicd/build_pyinstaller.sh
  .github/workflows/cicd.yml
Labels: maintenance

#237 update action trigger, add --access public to npm publish
  .github/workflows/cicd.yml
Labels: maintenance

#238 add scope to npm setup
  .github/workflows/cicd.yml
Labels: maintenance

#239 npm action fixes
  .github/workflows/cicd.yml
Labels: maintenance

#240 manually configure npm incase action config is causing failure
  .github/workflows/cicd.yml
Labels: maintenance

#241 fix npm publishing
  .github/workflows/cicd.yml
Labels: maintenance

#242 update pin of importlib-resources
  Pipfile
  Pipfile.lock
Labels: maintenance, skip-changelog

#243 revert removal of env var
  .github/workflows/cicd.yml
Labels: maintenance, skip-changelog

#244 deprecate support for python 3.5
  .github/workflows/cicd.yml
  CHANGELOG.md
  setup.py
Labels: feature

#246 Fix publishing on tags
  .github/workflows/cicd.yml
Labels: bug, maintenance, priority:high

#247 Fix non-dev npm deployments
  Makefile
Labels: maintenance

#248 only publish to test pypi on commits to master
  .github/workflows/cicd.yml
Labels: maintenance

#253 support an AWS SSO profile as the initial credential source
  CHANGELOG.md
  runway/aws_sso_botocore/__init__.py
  runway/aws_sso_botocore/credentials.py
  runway/aws_sso_botocore/exceptions.py
  runway/aws_sso_botocore/session.py
  runway/aws_sso_botocore/util.py
  runway/cfngin/session_cache.py
  runway/context.py
  runway/util.py
  setup.cfg
  tests/conftest.py
  tests/test_context.py
  tests/test_util.py
Labels: feature

#258 bump pylint and astroid versions, fix linting errors
  .github/workflows/cicd.yml
  Makefile
  Pipfile
  Pipfile.lock
  runway/cfngin/plan.py
  runway/cfngin/providers/aws/default.py
  runway/cfngin/util.py
  runway/commands/runway/gen_sample.py
  runway/commands/runway_command.py
  runway/env_mgr/kbenv.py
  runway/env_mgr/tfenv.py
  runway/sources/git.py
  runway/templates/k8s-tf-repo/eks-base.tf/get_idp_root_cert_thumbprint.py
  runway/variables.py
Labels: dependencies

#250 action to update urlshortener when a new version is published to s3
  .github/scripts/urlshortener/Makefile
  .github/scripts/urlshortener/Pipfile
  .github/scripts/urlshortener/Pipfile.lock
  .github/scripts/urlshortener/README.md
  .github/scripts/urlshortener/requirements.txt
  .github/scripts/urlshortener/setup.cfg
  .github/scripts/urlshortener/test_update_urls.py
  .github/scripts/urlshortener/update_urls.py
  .github/workflows/cicd.yml
  .gitignore
  .vscode/settings.json
  docs/source/developers/maintainers/index.rst
  docs/source/developers/maintainers/infrastructure.rst
  docs/source/developers/maintainers/release_process.rst
  infrastructure/Makefile
  infrastructure/README.md
  infrastructure/public/README.md
  infrastructure/public/common/bucket-and-user.cdk/.gitignore
  infrastructure/public/common/bucket-and-user.cdk/README.md
  infrastructure/public/common/bucket-and-user.cdk/bin/app.ts
  infrastructure/public/common/bucket-and-user.cdk/cdk.json
  infrastructure/public/common/bucket-and-user.cdk/lib/assets-stack.ts
  infrastructure/public/common/bucket-and-user.cdk/package-lock.json
  infrastructure/public/common/bucket-and-user.cdk/package.json
  infrastructure/public/common/bucket-and-user.cdk/tsconfig.json
  infrastructure/public/common/bucket-and-user.cdk/tslint.json
  infrastructure/public/common/runway.yml
Labels: maintenance

#254 add args option tf modules, improve option handling with dedicated classes
  .vscode/settings.json
  CHANGELOG.md
  docs/source/serverless/advanced_features.rst
  docs/source/terraform/advanced_features.rst
  docs/source/terraform/configuration.rst
  runway/module/__init__.py
  runway/module/terraform.py
  tests/module/test_module.py
  tests/module/test_terraform.py
Labels: feature

#257 remove issue management action, assign and label are now in the template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/general_question.md
  .github/workflows/issue-management.yml
  docs/source/developers/github_actions.rst
Labels: maintenance
