Repository rackspace/runway, pull requests merged in 2021-03, with the labels that each got.

#551 update sls-tsc sample to use serialized compilation
  CHANGELOG.md
  runway/templates/sls-tsc/package.json
  runway/templates/sls-tsc/serverless.yml
Labels: feature, priority:low

#556 remove profile field from cfngin config
  runway/cfngin/actions/base.py
  runway/cfngin/stack.py
  runway/config/models/cfngin/__init__.py
  tests/unit/config/models/cfngin/test_cfngin.py
  tests/unit/core/providers/aws/test_cli.py
Labels: breaking, feature, major

#558 add `schema cfngin` & `schema runway` commands
  docs/source/commands.rst
  runway/_cli/commands/__init__.py
  runway/_cli/commands/_schema/__init__.py
  runway/_cli/commands/_schema/_cfngin.py
  runway/_cli/commands/_schema/_runway.py
  tests/integration/cli/commands/test_schema.py
  tests/integration/cli/commands/test_schema_cfngin.py
  tests/integration/cli/commands/test_schema_runway.py
Labels: feature, minor

#559 update dependencies
  Pipfile
  Pipfile.lock
  docs/Pipfile.lock
  docs/requirements.txt
  integration_test_infrastructure/Pipfile.lock
  integration_tests/Pipfile.lock
  runway/cfngin/blueprints/base.py
Labels: dependencies, python, skip-changelog

#561 replace `init` command with `new` command
  README.md
  docs/source/commands.rst
  docs/source/getting_started.rst
  runway/_cli/commands/__init__.py
  runway/_cli/commands/_init.py
  runway/_cli/commands/_new.py
  tests/integration/cli/commands/test_init.py
  tests/integration/cli/commands/test_new.py
  tests/integration/cli/commands/test_schema.py
Labels: feature, major

#562 remove `region` field from cfngin stack configuration
  runway/cfngin/actions/base.py
  runway/cfngin/actions/deploy.py
  runway/cfngin/actions/destroy.py
  runway/cfngin/actions/diff.py
  runway/cfngin/actions/info.py
  runway/cfngin/hooks/base.py
  runway/cfngin/stack.py
  runway/config/models/cfngin/__init__.py
  tests/unit/cfngin/hooks/test_base.py
  tests/unit/config/models/cfngin/test_cfngin.py
Labels: feature, major

#564 update pull request template
  .github/pull_request_template.md
Labels: maintenance, skip-changelog

#563 tfenv: log hcl errors & return empty dict if module can't be parsed
  Makefile
  pyproject.toml
  runway/env_mgr/tfenv.py
  runway/exceptions.py
  tests/unit/env_mgr/test_tfenv.py
Labels: feature, minor

#569 explicit exception chaining & exception base class
  Makefile
  pyproject.toml
  runway/aws_sso_botocore/credentials.py
  runway/aws_sso_botocore/util.py
  runway/cfngin/blueprints/base.py
  runway/cfngin/environment.py
  runway/cfngin/exceptions.py
  runway/cfngin/hooks/aws_lambda.py
  runway/cfngin/hooks/docker/data_models.py
  runway/cfngin/hooks/utils.py
  runway/cfngin/lookups/handlers/default.py
  runway/cfngin/lookups/handlers/dynamodb.py
  runway/cfngin/lookups/handlers/envvar.py
  runway/cfngin/lookups/handlers/file.py
  runway/cfngin/lookups/handlers/output.py
  runway/cfngin/lookups/handlers/split.py
  runway/cfngin/plan.py
  runway/cfngin/util.py
  runway/config/components/runway/base.py
  runway/context/cfngin.py
  runway/exceptions.py
  runway/hooks/staticsite/auth_at_edge/templates/shared_jose.py
  runway/lookups/handlers/cfn.py
  tests/unit/cfngin/test_stack.py
  tests/unit/context/test_cfngin.py
Labels: feature, minor
