Repository rackspace/runway, pull requests merged in 2021-01, with the labels that each got.

#504 sls-tsc sample: update typedoc dependency to remove beta requirement
  CHANGELOG.md
  runway/templates/sls-tsc/package.json
Labels: dependencies, priority:low

#505 k8s samples: drop unneeded IAM policy
  CHANGELOG.md
  runway/blueprints/k8s/k8s_master.py
  runway/templates/k8s-cfn-repo/_gitignore
  runway/templates/k8s-cfn-repo/runway.yml
  runway/templates/k8s-tf-repo/_gitignore
  runway/templates/k8s-tf-repo/eks-base.tf/main.tf
  runway/templates/k8s-tf-repo/job-s3-echo.tf/main.tf
Labels: enhancement, priority:low

#493 add docker cfngin hook
  .pre-commit-config.yaml
  .vscode/settings.json
  CHANGELOG.md
  Makefile
  Pipfile
  Pipfile.lock
  docs/source/cfngin/hooks.rst
  docs/source/cfngin/lookups.rst
  docs/source/conf.py
  docs/source/lookups.rst
  runway/cfngin/hooks/aws_lambda.py
  runway/cfngin/hooks/docker/__init__.py
  runway/cfngin/hooks/docker/_login.py
  runway/cfngin/hooks/docker/data_models.py
  runway/cfngin/hooks/docker/hook_data.py
  runway/cfngin/hooks/docker/image/__init__.py
  runway/cfngin/hooks/docker/image/_build.py
  runway/cfngin/hooks/docker/image/_push.py
  runway/cfngin/hooks/docker/image/_remove.py
  runway/cfngin/hooks/ecr/__init__.py
  runway/cfngin/hooks/ecr/_purge_repository.py
  runway/cfngin/lookups/registry.py
  runway/core/providers/__init__.py
  runway/lookups/handlers/__init__.py
  runway/lookups/handlers/ecr.py
  runway/lookups/registry.py
  runway/util.py
  tests/unit/cfngin/actions/test_diff.py
  tests/unit/cfngin/hooks/docker/__init__.py
  tests/unit/cfngin/hooks/docker/image/__init__.py
  tests/unit/cfngin/hooks/docker/image/test_build.py
  tests/unit/cfngin/hooks/docker/image/test_push.py
  tests/unit/cfngin/hooks/docker/image/test_remove.py
  tests/unit/cfngin/hooks/docker/test_data_models.py
  tests/unit/cfngin/hooks/docker/test_hook_data.py
  tests/unit/cfngin/hooks/docker/test_login.py
  tests/unit/cfngin/hooks/ecr/__init__.py
  tests/unit/cfngin/hooks/ecr/test_purge_repositroy.py
  tests/unit/cfngin/hooks/test_aws_lambda.py
  tests/unit/conftest.py
  tests/unit/factories.py
  tests/unit/fixtures/blueprints/test_repo.json-result
  tests/unit/lookups/handlers/test_ecr.py
  tests/unit/lookups/test_registry.py
  tests/unit/mock_docker/__init__.py
  tests/unit/mock_docker/fake_api.py
  tests/unit/mock_docker/fake_api_client.py
  tests/unit/mock_docker/fake_stat.py
Labels: feature

#507 Revert GitHub Actions Ubuntu 20.04 upgrade
  .github/scripts/cicd/build_pyinstaller.sh
  .github/workflows/branch-name.yml
  .github/workflows/cicd.yml
  .github/workflows/publish-on-release.yml
  .github/workflows/release-management.yml
  CHANGELOG.md
  docs/source/developers/pyinstaller.rst
  docs/source/maintainers/release_process.rst
Labels: bug, priority:medium

#512 remove Stacker CLI components & deprecated `run-stacker` command
  docs/source/commands.rst
  integration_tests/test_commands/tests/test_stacker.py
  runway/_cli/commands/__init__.py
  runway/_cli/commands/_run_stacker.py
  runway/cfngin/commands/__init__.py
  runway/cfngin/commands/stacker/__init__.py
  runway/cfngin/commands/stacker/base.py
  runway/cfngin/commands/stacker/build.py
  runway/cfngin/commands/stacker/destroy.py
  runway/cfngin/commands/stacker/diff.py
  runway/cfngin/commands/stacker/graph.py
  runway/cfngin/commands/stacker/info.py
  runway/cfngin/hooks/aws_lambda.py
  runway/cfngin/util.py
  scripts/stacker-runway
  scripts/stacker-runway.cmd
  setup.py
  tests/integration/cli/commands/test_run_stacker.py
  tests/unit/cfngin/test_stacker.py
  tests/unit/cfngin/test_util.py
Labels: feature

#522 remove `targets` field from CFNgin config
  runway/cfngin/actions/base.py
  runway/cfngin/actions/build.py
  runway/cfngin/plan.py
  runway/cfngin/target.py
  runway/config/__init__.py
  runway/config/models/cfngin/__init__.py
  runway/context/cfngin.py
  tests/unit/config/models/cfngin/test_cfngin.py
  tests/unit/context/test_cfngin.py
Labels: feature

#523 remove stacker argv override that was left over from using parts of CLI
  runway/cfngin/cfngin.py
  tests/unit/cfngin/test_cfngin.py
Labels: feature

#524 improve module base classes, move module base classes and utilities
  docs/source/developers/custom_module.rst
  runway/core/components/_module.py
  runway/exceptions.py
  runway/module/__init__.py
  runway/module/base.py
  runway/module/cdk.py
  runway/module/cloudformation.py
  runway/module/k8s.py
  runway/module/serverless.py
  runway/module/staticsite.py
  runway/module/terraform.py
  runway/module/utils.py
  runway/runway_module_type.py
  runway/util.py
  tests/unit/core/components/test_module.py
  tests/unit/module/conftest.py
  tests/unit/module/test_base.py
  tests/unit/module/test_cloudformation.py
  tests/unit/module/test_module.py
  tests/unit/module/test_serverless.py
  tests/unit/module/test_terraform.py
  tests/unit/module/test_utils.py
  tests/unit/test_runway_module_type.py
Labels: feature

#525 move, rename, & update the module path class
  docs/source/runway_config.rst
  runway/core/components/__init__.py
  runway/core/components/_module.py
  runway/core/components/_module_path.py
  runway/path.py
  runway/sources/git.py
  tests/unit/conftest.py
  tests/unit/core/components/test_module.py
  tests/unit/core/components/test_module_path.py
  tests/unit/test_path.py
Labels: feature
