Repository rackspace/runway, pull requests merged in 2021-02, with the labels that each got.

#527 account_alias & account_id: remove environment map support
  docs/source/runway_config.rst
  infrastructure/public/common/runway.yml
  integration_test_infrastructure/codebuild/common/runway.yml
  runway/config/components/runway/_deployment_def.py
  runway/config/models/runway/__init__.py
  runway/core/components/_deployment.py
  tests/unit/config/models/runway/test_runway.py
  tests/unit/core/components/test_deployment.py
  tests/unit/fixtures/deployments/validate_account_map.yml
Labels: feature

#528 sls: use pydantic model to parse options
  runway/config/models/runway/options/__init__.py
  runway/config/models/runway/options/serverless.py
  runway/module/base.py
  runway/module/serverless.py
  tests/unit/config/models/runway/options/__init__.py
  tests/unit/config/models/runway/options/test_serverless.py
  tests/unit/module/test_serverless.py
Labels: feature

#529 tf: use pydantic model to parse options
  runway/config/models/runway/options/terraform.py
  runway/module/base.py
  runway/module/serverless.py
  runway/module/terraform.py
  tests/unit/config/models/runway/options/test_terraform.py
  tests/unit/module/test_base.py
  tests/unit/module/test_terraform.py
Labels: feature

#530 cdk: use pydantic model to parse options
  runway/config/models/runway/options/cdk.py
  runway/module/cdk.py
  tests/unit/config/models/runway/options/test_cdk.py
  tests/unit/module/test_cdk.py
Labels: feature

#531 k8s: use pydantic model to parse options
  runway/config/models/runway/options/k8s.py
  runway/module/k8s.py
  runway/module/terraform.py
  tests/unit/config/models/runway/options/test_k8s.py
  tests/unit/module/test_k8s.py
Labels: feature

#532 staticsite: use pydantic model to parse options and parameters
  docs/source/staticsite/configuration.rst
  runway/blueprints/staticsite/dependencies.py
  runway/core/components/_module_type.py
  runway/module/base.py
  runway/module/staticsite/__init__.py
  runway/module/staticsite/handler.py
  runway/module/staticsite/options/__init__.py
  runway/module/staticsite/options/components.py
  runway/module/staticsite/options/models.py
  runway/module/staticsite/parameters/__init__.py
  runway/module/staticsite/parameters/models.py
  runway/module/staticsite/utils.py
  tests/unit/core/components/test_module_type.py
  tests/unit/module/staticsite/__init__.py
  tests/unit/module/staticsite/options/__init__.py
  tests/unit/module/staticsite/options/test_components.py
  tests/unit/module/staticsite/options/test_models.py
  tests/unit/module/staticsite/parameters/__init__.py
  tests/unit/module/staticsite/parameters/test_models.py
  tests/unit/module/staticsite/test_handler.py
Labels: feature

#537 sls-tsc sample: drop legacy aws-sdk and bump node version
  runway/templates/sls-tsc/package.json
  runway/templates/sls-tsc/serverless.yml
  runway/templates/sls-tsc/webpack.config.js
Labels: maintenance, priority:low

#540 variable: support concatenating int and str
  runway/variables.py
  tests/unit/test_variables.py
Labels: feature

#541 cli: deployment regions menu entry show lookup string if unresolved
  runway/_cli/utils.py
  runway/config/components/runway/_deployment_def.py
  runway/exceptions.py
  tests/unit/config/components/runway/test_deployment_def.py
Labels: bug

#542 config: replace module type enum with literal, update type annotations
  runway/config/components/runway/_module_def.py
  runway/config/models/runway/__init__.py
  runway/core/components/__init__.py
  runway/core/components/_module.py
  runway/core/components/_module_type.py
  tests/unit/core/components/test_module.py
  tests/unit/core/components/test_module_type.py
Labels: feature, skip-changelog

#543 cfngin: change `pre_/post_build` to `pre_/post_deploy` to match terminology
  docs/source/cfngin/configuration.rst
  docs/source/cfngin/hooks.rst
  docs/source/cfngin/lookups.rst
  docs/source/cfngin/migrating.rst
  docs/source/terminology.rst
  integration_tests/test_cfngin/tests/fixtures/16_aws_lambda_hook.yaml
  runway/cfngin/actions/deploy.py
  runway/cfngin/actions/destroy.py
  runway/cfngin/actions/diff.py
  runway/cfngin/cfngin.py
  runway/cfngin/hooks/acm.py
  runway/cfngin/hooks/aws_lambda.py
  runway/cfngin/hooks/base.py
  runway/cfngin/hooks/command.py
  runway/cfngin/hooks/docker/_login.py
  runway/cfngin/hooks/docker/image/_build.py
  runway/cfngin/hooks/docker/image/_push.py
  runway/cfngin/hooks/docker/image/_remove.py
  runway/cfngin/hooks/utils.py
  runway/cfngin/plan.py
  runway/cfngin/providers/aws/default.py
  runway/cfngin/stack.py
  runway/config/__init__.py
  runway/config/models/cfngin/__init__.py
  runway/lookups/handlers/ecr.py
  runway/module/cloudformation.py
  runway/module/staticsite/handler.py
  runway/templates/k8s-cfn-repo/k8s-master.cfn/stacks.yaml
  runway/templates/k8s-cfn-repo/k8s-workers.cfn/stacks.yaml
  runway/templates/k8s-tf-repo/gen-kubeconfig.cfn/hooks.yaml
  tests/unit/cfngin/actions/test_deploy.py
  tests/unit/cfngin/fixtures/vpc-bastion-db-web-pre-1.0.yaml
  tests/unit/cfngin/fixtures/vpc-bastion-db-web.yaml
  tests/unit/cfngin/hooks/test_base.py
  tests/unit/cfngin/hooks/test_utils.py
  tests/unit/cfngin/test_cfngin.py
  tests/unit/cfngin/test_util.py
  tests/unit/config/models/cfngin/test_cfngin.py
Labels: feature

#544 fix lambda zip errors when docker creates files as root
  runway/cfngin/hooks/aws_lambda.py
Labels: bug, priority:medium

#545 force multiprocessing to fork processes & disable parallel on non-posix systems
  pyproject.toml
  runway/context/base.py
  runway/context/runway.py
  runway/context/sys_info.py
  runway/core/components/_deployment.py
  runway/core/components/_module.py
  tests/unit/conftest.py
  tests/unit/context/test_base.py
  tests/unit/context/test_runway.py
  tests/unit/context/test_sys_info.py
  tests/unit/core/components/test_deployment.py
  tests/unit/core/components/test_module.py
Labels: bug

#549 avoid awscli instantiation during kbenv
  runway/_cli/commands/_run_aws.py
  runway/core/providers/aws/_cli.py
  tests/unit/core/providers/aws/test_cli.py
Labels: bug, priority:low
