Repository rackspace/runway, pull requests merged in 2024-09, with the labels that each got.

#2483 update repository URLs to reflect transfer of repository ownership
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/cicd.yml
  .github/workflows/label-maker.yml
  CODE_OF_CONDUCT.md
  LICENSE
  README.md
  docs/source/cfngin/blueprints.rst
  docs/source/cfngin/remote_sources.rst
  docs/source/changelog.rst
  docs/source/conf.py
  docs/source/license.rst
  docs/source/maintainers/release_process.rst
  docs/source/quickstart/cloudformation.rst
  docs/source/quickstart/conduit.rst
  docs/source/quickstart/other_ways_to_use.rst
  docs/source/serverless/advanced_features.rst
  infrastructure/test-alt/common/iam.cfn/cfngin.yml
  infrastructure/test-alt/common/test-dependencies.cfn/cfngin.yml
  infrastructure/test/common/iam.cfn/cfngin.yml
  infrastructure/test/common/test-dependencies.cfn/cfngin.yml
  pyproject.toml
  quickstarts/conduit/pyproject.toml
  quickstarts/conduit/runway.yml
  runway/config/models/cfngin/_package_sources.py
  runway/templates/cdk-csharp/package.json
  runway/templates/cdk-py/package.json
  runway/templates/cdk-py/pyproject.toml
  runway/templates/sls-py/pyproject.toml
  tests/functional/cfngin/hooks/test_awslambda/sample_app/src/docker_xmlsec/pyproject.toml
  tests/functional/sources/git/runway.yml
  tests/unit/core/components/test__module_path.py
  tests/unit/sources/test_git.py
Labels: maintenance, javascript, python, github_actions, poetry

#2544 remove CDK deprecation message
  runway/module/cdk.py
Labels: feature, changelog:patch

#2547 delete files in `.terraform` rather than sending them to trash
  poetry.lock
  pyproject.toml
  runway/module/terraform.py
Labels: bug, python, changelog:minor, poetry

#2523 replace dependabot with renovate
  .github/dependabot.yml
  .github/labels.yml
  .github/release-drafter.yml
  .github/renovate.json
  .github/workflows/label-maker.yml
Labels: maintenance, github_actions

#2568 add pre-commit.ci badge and remove workflow setup
  .github/workflows/cicd.yml
  README.md
Labels: maintenance

#2586 add id-token permissions for trusted publish to pypi
  .github/workflows/release.yml
  .vscode/dictionaries/pypi.txt
Labels: maintenance, changelog:skip

#2587 update renovate config to group boto3, ignore quickstart python deps
  .github/renovate.json
Labels: maintenance, changelog:skip, dependencies
