Repository rackspace/runway, pull requests merged in 2024-11, with the labels that each got.

#2598 improve devcontainer
  .devcontainer/.editorconfig
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/files/.bash_completion
  .devcontainer/local-features/README.md
  .devcontainer/local-features/poetry/README.md
  .devcontainer/local-features/poetry/devcontainer-feature.json
  .devcontainer/local-features/poetry/install.sh
  .vscode/cspell.json
  .vscode/extensions.json
  docs/source/conf.py
  docs/source/developers/getting_started.rst
Labels: maintenance

#2647 test_multistack upgrade of CDK to v2
  tests/functional/cdk/test_multistack/bin/stacks.ts
  tests/functional/cdk/test_multistack/cdk.json
  tests/functional/cdk/test_multistack/lib/example-stack.ts
  tests/functional/cdk/test_multistack/package-lock.json
  tests/functional/cdk/test_multistack/package.json
  tests/functional/cdk/test_multistack/tsconfig.json
Labels: maintenance, changelog:skip

#2654 add setting to explicitly set automergeStrategy to squach
  .github/renovate.json
Labels: maintenance

#2672 replace `:` with `=` to avoid YAML error in some jinja use cases
  runway/cfngin/providers/aws/default.py
  tests/unit/cfngin/providers/aws/test_default.py
Labels: bug, changelog:patch
