Repository rackspace/runway, pull requests merged in 2025-03, with the labels that each got.

#2777 `runway.cfngin.hooks.awslambda` now checks for restricted args
  runway/cfngin/hooks/awslambda/models/args.py
  tests/unit/cfngin/hooks/awslambda/models/test_args.py
Labels: feature, changelog:patch

#2776 recommend `detachhead.basedpyright` instead of `pylance`
  .vscode/extensions.json
  .vscode/settings.json
Labels: maintenance, changelog:skip

#2778 update CFNgin confgin file exclude regex to include docker-compose
  runway/config/__init__.py
Labels: bug, changelog:patch

#2780 add filtering for when functional tests should be run
  .github/workflows/cicd.yml
Labels: maintenance, changelog:skip

#2790 resolve functional test errors
  tests/functional/cfngin/hooks/test_awslambda/sample_app/src/docker_mysql/Dockerfile
  tests/functional/cfngin/hooks/test_awslambda/sample_app/src/docker_xmlsec/Dockerfile
  tests/functional/cfngin/hooks/test_awslambda/sample_app/src/docker_xmlsec/pyproject.toml
Labels: maintenance, changelog:skip

#2801 add docs for maintenance branches
  .github/workflows/label-maker.yml
  .github/workflows/spell-check.yml
  docs/source/maintainers/maintenance_branches.rst
  docs/source/maintainers/release_process.rst
Labels: documentation
